create table SYS.INPUT_FILE_ERROR_DATA (
 	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,   
	FILE_ID BIGINT NOT NULL,
   	ERROR  VARCHAR(1000) default NULL,
   	LOAD_TIME TIMESTAMP default CURRENT_TIMESTAMP);