create table SYS.INPUT_FILE_DATA (
   FIELD_DATA_ID INT NOT NULL AUTO_INCREMENT,
   LOAD_DATE DATE default NULL,
   WEB_SITE  VARCHAR(200) default NULL,
   VISIT_COUNT  LONG  default NULL,
   LOAD_TIME TIMESTAMP default CURRENT_TIMESTAMP,
   UNIQUE KEY (FIELD_DATA_ID, LOAD_DATE)
)
PARTITION BY KEY(FIELD_DATA_ID,LOAD_DATE);