create table SYS.INPUT_FILE_DATA (
   FILE_DATA_ID INT NOT NULL AUTO_INCREMENT,
   FILE_ID INT NOT NULL,
   LOAD_DATE DATE default NULL,
   WEB_SITE  VARCHAR(200) default NULL,
   VISIT_COUNT  LONG  default NULL,
   LOAD_TIME TIMESTAMP default CURRENT_TIMESTAMP,
   UNIQUE KEY (FILE_DATA_ID, LOAD_DATE)
)
PARTITION BY KEY(FILE_DATA_ID,LOAD_DATE);