create table SYS.USER_LOGIN (
   ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   USER_ID  VARCHAR(200) default NULL,
   PASSWORD  VARCHAR(200) default NULL,
   LAST_LOGIN_TIME TIMESTAMP default CURRENT_TIMESTAMP
)
PARTITION BY KEY(ID);