create table SYS.USER_DETAILS (
   USER_ID  VARCHAR(200) PRIMARY KEY NOT NULL,
   USER_NAME  VARCHAR(200) default NULL,
   EMAIL_ID  VARCHAR(200) default NULL,
   PHONE_NUMBER DECIMAL ,
   COUNTRY  VARCHAR(50) default NULL,
   SEQUERY_QUESTION VARCHAR(200) default NULL,
   SEQUERY_ANSWER VARCHAR(200) default NULL,
   CREATED_TIME TIMESTAMP default CURRENT_TIMESTAMP
)
PARTITION BY KEY(USER_ID);